config/routes.rb
Rails.application.routes.draw do
  	
  	devise_for :users

  	root "recipes#index"
	
	resources :recipes do
		member do
			put "like" => "recipes#upvote"
			put "unlike" => "recipes#downvote"			
		end
	end
	

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/direction.rb
class Direction < ApplicationRecord
  belongs_to :recipe#, inverse_of: :directions
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :recipe#, inverse_of: :ingredients
end

app/models/recipe.rb
class Recipe < ApplicationRecord

	# This is for user and make relation with recipe
	belongs_to :user

	# This is the voting votable for user
	acts_as_votable

	# add inverse_of because I cannot save the ingredients. Stackoverflow said
	# When you include the inverse_of, rails now knows about those associations and will "match" them in memory.
	has_many :ingredients, inverse_of: :recipe
	has_many :directions, inverse_of: :recipe
	# This is the script to add ingredients and directions the form, got from cocoon gem and mackenzie child tips
	# to add form under the new recipe form and allow only if forms filled properly
	accepts_nested_attributes_for :ingredients, 
								   reject_if: proc { |attributes| attributes['name'].blank?}, 
								   allow_destroy: true
	accepts_nested_attributes_for :directions, 
								   reject_if: proc { |attributes| attributes['step'].blank?}, 
								   allow_destroy: true

	# This is the script to make user validation error if they don't have any title, image and description
	validates :title, :description, :image, presence: true

	# and this is to upload image and control the filename extension bt paperclip gem
	has_attached_file :image, styles: { 
		thumb: '100x100>',
		square: '200x200#',
		medium: "400x400#", 
	}
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

	# This is to find out the last 12 characters youtube digit
	def youtube_code
		return if video.nil?
			
			# This is the code that mike taught me but it didn't recognize nil or youtube share link with / characters
			# url = URI.parse(video)
			# url.query.split('=').last
		
		url = URI.parse(video)
		url.query.try(:split, '=').try(:last) || self.video.try(:split, '/').try(:last) 
	end
end

app/models/user.rb
class User < ApplicationRecord

  has_many :recipes
  has_many :likes

  # to make user can vote
  acts_as_voter

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable	

  # Virtual attribute for authenticating by either username or email
  # This is in addition to a real persisted field like 'username'
  def login=(login)
    @login = login
  end

  def login
    @login || self.username || self.email
  end
  
  # override devise look up to give username and email valid on login
  def self.find_for_database_authentication(warden_conditions)
  	conditions = warden_conditions.dup
  	if login = conditions.delete(:login)
  	  where(conditions.to_hash).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
  	elsif conditions.has_key?(:username) || conditions.has_key?(:email)
  	  where(conditions.to_hash).first
  	end
  end

  # to validate if user has empty space on login or sign up
  # validate :check_empty_space

  # def check_empty_space
  #   if self.attribute.match(/\s+/)
  #     errors.add(:attribute, "No empty spaces please :(")
  #   end
  # end

  # to be very careful with username validation, because there might be conflict between username and email. 
  validate :validate_username

  def validate_username
    if User.where(email: username).exists?
      errors.add(:username, :invalid)
    end
  end

  # this is to upload user avatar
  has_attached_file :avatar, :styles => { 
    :medium => "300x300>",
    :square => "200x200>",
    :thumb => "100x100#" }, :default_url => "/assets/images/missing-user.jpg"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  # Add login as an attr_accessor for devise as devise wiki asked for it
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  # actually on docs said we need to use devise_parameter_sanitizer.for but on rails +4.1 we use devise_parameter_sanitizer.permit
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.permit(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password, :avatar) }
  end

  def login=(login)
    @login = login
  end

  def login
    @login || self.username || self.email
  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
	before_action :find_recipe, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
	before_action :authenticate_user!, except: [:index, :show]


	def index
		@recipe = Recipe.all.order("created_at DESC")
	end

	def show
	end

	def new
		@recipe = current_user.recipes.build
	end

	def create
		@recipe = Recipe.new(recipe_params)
		@recipe.user_id = current_user.id

		puts @recipe.inspect

		if @recipe.save
			# show a success flash message and redirect to the recipe show page
			redirect_to @recipe, notice: "Successfully created your recipe"
		else
			# show fail flash message and render to new page for another shot to creating a recipe
			render 'new'
		end
	end

	def edit
	end

	def update
		if @recipe.update(recipe_params)
			# display a success flash and redirect to recipe show page
			redirect_to @recipe
		else
			# display an alert flasha remain on edit page
			render 'edit'
		end
	end

	def destroy
		@recipe.destroy
		redirect_to root_path, notice: "Successfully deleted recipe"
	end

	# upvote and downvote from user

	def upvote
		@recipe.upvote_from current_user
		redirect_to root_path
	end

	def downvote
		@recipe.downvote_from current_user
		redirect_to root_path
	end

	private

	def recipe_params
		# As I don't trust parameters from scary internet, this is only allow the white list
		params.require(:recipe).permit(:title, :description, :image, :avatar, :video,
			ingredients_attributes: [:id, :name, :_destroy], 
			directions_attributes: [:id, :step, :_destroy])

	end

	def find_recipe
		# use callbacks to share common setup setup por constrains between actions
		@recipe = Recipe.find(params[:id])

	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.erb
<html></html>
<head>
  <title>Foodlof</title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
  
    <div class="navbar navbar-default navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle Navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>

        <div class="navbar-brand">
          <%= link_to "Foodlof", root_path %>
        </div>

      </div> <!-- end div class="navbar-header" -->

      <div class="collapse navbar-collapse">
        <% if user_signed_in? %>
          <ul class="nav navbar-nav navbar-right">
            <li class="active">
              <%= link_to "New Recipe | ", new_recipe_path %>
            </li>
            <li>
              <%= link_to "Sign Out | ", destroy_user_session_path, method: :delete %>
            </li>
            <li>
            <li>
              <%= link_to image_tag(current_user.avatar.url(:thumb), :size => "40x40", class: "avatar-style"), edit_user_registration_path %>
            </li>
          </ul>
        <% else %>
          <ul class="nav navbar-nav navbar-right bg-menu-collapse">
            <li>
              <%= link_to new_user_registration_path do %>
                <i class="glyphicon glyphicon-user"> </i> Sign Up
            <% end %>
            </li>
            <li>
              <%= link_to new_user_session_path do %>
                <i class="glyphicon glyphicon-log-in"> </i> Login
            <% end %>
            </li>
          </ul>
        <% end %>
      </div> <!-- end div class="collapse navbar-collapse" -->
    </div> <!-- end div class="container" -->
  </div> <!-- end div class="navbar navbar-default navbar-fixed-top" -->

  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, class: "Alert" %>
    <% end %>
    <%= yield %>
  </div>
</body>

app/views/layouts/application.html.haml
%html
%head
	%title Foodloov
	= csrf_meta_tags
	= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
	= javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

%body
	%nav.navbar.navbar-default
		.container
			.navbar-brand= link_to "Foodloov", root_path

			- if user_signed_in?
				%ul.nav.navbar-nav.navbar-right
					%li= link_to "New Recipe", new_recipe_path
					%li= link_to "Sign Out", destroy_user_session_path, method: :delete
			- else
				%ul.nav.navbar-nav.navbar-right
					%li= link_to "Sign Up", new_user_registration_path
					%li= link_to "Login", new_user_session_path

	.container
		- flash.each do |name, msg|
			= content_tag :div, msg, class: "Alert"
		
		= yield

app/views/recipes/_direction_fields.html.erb
<div class="form-inline clearfix">
  <div class="nested-fields">
    <%= f.input :step, input_html: { class: 'form-input form-control' } %>
    <%= link_to_remove_association "Remove Step", f, class: "btn btn-default form-button" %>
  </div>
</div>

app/views/recipes/_direction_fields.html.haml
.form-inline.clearfix
	.nested-fields
		= f.input :step, input_html: { class: 'form-input form-control' }
		= link_to_remove_association "Remove Step", f, class: "btn btn-default form-button"

app/views/recipes/_form.html.erb
<%= simple_form_for @recipe, html: { multipart: true } do |f| %>
  <% if @recipe.errors.any? %>
    <div id="errors">
      <p>
        <%= @recipe.errors.count %>
        Prevented this recipe froms saving
      </p>
      <ul>
        <% @recipe.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="panel-body">
    <%= f.input :title, input_html: { class: 'form-control' } %>
    <%= f.input :description, input_html: { class: 'form-control' } %>
    <%= f.input :image, input_html: { class: 'form-control' } %>
    <%= f.input :video, input_html: { class: 'form-control' } %>
    <div class="row">
      <div class="col-md-6">
        <h3>Ingredients</h3>
        <div id="ingredients">
          <%= f.simple_fields_for :ingredients do |ingredient| %>
            <%= render 'ingredient_fields', f: ingredient %>
          <% end %>
          <div class="links">
            <%= link_to_add_association 'Add Ingredient', f, :ingredients, class: "btn btn-default add-button" %>
          </div>
        </div>
      </div>
      <div class="col-md-6">
        <h3>Directions</h3>
        <div id="directions">
          <%= f.simple_fields_for :directions do |direction| %>
            <%= render 'direction_fields', f: direction %>
          <% end %>
          <div class="links">
            <%= link_to_add_association 'Add Step', f, :directions, class: "btn btn-default add-button" %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/recipes/_form.html.haml
= simple_form_for @recipe, html: { multipart: true } do |f|
	- if @recipe.errors.any?
		#errors
			%p
				= @recipe.errors.count
				Prevented this recipe froms saving
			%ul
				- @recipe.errors.full_messages.each do |msg|
					%li= msg
	.panel-body
		= f.input :title, input_html: { class: 'form-control' }
		= f.input :description, input_html: { class: 'form-control' }
		= f.input :image, input_html: { class: 'form-control' }
		= f.input :video, input_html: { class: 'form-control' }

		.row
			.col-md-6
				%h3 Ingredients
				#ingredients
					= f.simple_fields_for :ingredients do |ingredient|
						= render 'ingredient_fields', f: ingredient
					.links
						= link_to_add_association 'Add Ingredient', f, :ingredients, class: "btn btn-default add-button"

			.col-md-6
				%h3 Directions
				#directions
					= f.simple_fields_for :directions do |direction|
						= render 'direction_fields', f: direction
					.links
						= link_to_add_association 'Add Step', f, :directions, class: "btn btn-default add-button"

	= f.button :submit, class: "btn btn-primary"

app/views/recipes/_ingredient_fields.html.erb
<div class="form-inline clearfix">
  <div class="nested-fields">
    <%= f.input :name, input_html: { class: 'form-input form-control' } %>
    <%= link_to_remove_association "Remove", f, class: "form-button btn btn-default" %>
  </div>
</div>

app/views/recipes/_ingredient_fields.html.haml
.form-inline.clearfix
	.nested-fields
		= f.input :name, input_html: { class: 'form-input form-control' }
		= link_to_remove_association "Remove", f, class: "form-button btn btn-default"

app/views/recipes/_likes.html.erb
<div class="caption" style="text-align: left; padding: 0 0 10px 0;">
	<%= link_to like_recipe_path(recipe), class: "like", method: :put do %>
		<button type="button" class="btn btn-primary" aria-label="Left Align">
			<span class="glyphicon glyphicon-heart" aria-hidden="true"></span>
			<span class="badge"><%= recipe.get_upvotes.size %></span>
		</button>
	<% end %>

	<%= link_to unlike_recipe_path(recipe), class: "like", method: :put do %>
		<!-- <button type="button" class="btn btn-info" aria-label="Left Align">
		<span class="glyphicon glyphicon glyphicon-heart-empty glyphicon-align-center" aria-hidden="true"></span>
		<span class="badge"><%= recipe.get_downvotes.size %></span> -->
		</button>
	<% end %>
</div>

app/views/recipes/edit.html.erb
<h1>Edit Recipe</h1>
<%= render 'form' %>

app/views/recipes/edit.html.haml
%h1 Edit Recipe

= render 'form'

app/views/recipes/index.html.erb
<% @recipe.each_slice(3) do |recipes| %>
  <div class="row">
    <% recipes.each do |recipe| %>
      <div class="col-md-4">
        <div class="recipe">
          <div class="image_wrapper">
            <%= link_to recipe do %>
              <%= image_tag recipe.image.url(:medium)  %>
            <% end %>
          </div>
          <h2>
            <%= link_to recipe.title, recipe %>
          </h2>
          
          <br>

          <div class="caption" style="text-align: left; padding: 0 0 10px 0;">
            <%= link_to like_recipe_path(recipe), class: "like", method: :put do %>
              <button type="button" class="btn btn-primary" aria-label="Left Align">
                <span class="glyphicon glyphicon-heart" aria-hidden="true"></span>
                <span class="badge"><%= recipe.get_upvotes.size %></span>
              </button>
            <% end %>

            <%= link_to unlike_recipe_path(recipe), class: "like", method: :put do %>
              <button type="button" class="btn btn-info" aria-label="Left Align">
                <span class="glyphicon glyphicon glyphicon-heart-empty glyphicon-align-center" aria-hidden="true"></span>
                <span class="badge"><%= recipe.get_downvotes.size %></span>
              </button>
            <% end %>
          </div>

        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/recipes/index.html.haml
- @recipe.each_slice(3) do |recipes|
	.row
		-recipes.each do |recipe|
			.col-md-4
				.recipe
					.image_wrapper
						= link_to recipe do
							= image_tag recipe.image.url(:medium) 
					%h2= link_to recipe.title, recipe

app/views/recipes/new.html.erb
<h1>New Recipe</h1>
<%= render 'form' %>
<br/>
<%= link_to "Back", root_path, class: "btn btn-default" %>

app/views/recipes/new.html.haml
%h1 New Recipe

= render 'form'

%br/

= link_to "Back", root_path, class: "btn btn-default"

app/views/recipes/show.html.erb
<div class="main_content">
  <div class="row" id="recipe_top">
    <div class="col-md-4">
      <%= image_tag @recipe.image.url(:medium), class: "recipe_image" %>
    </div>
    <div class="col-md-8">
      <div id="recipe_info">
        <% # this is the recipe title %>
        <h1>
          <%= @recipe.title %>
        </h1>
        <% # this is the recipe author email %>
        <p>
          Submited by
          <%= @recipe.user.username %>
        </p>
        <% # this is the recipe description %>
        <p class="description">
          <%= @recipe.description %>
        </p>
      </div>

      
    </div>
  </div>
  <div class="row">
    <div class="col-md-4">
      <div id="ingredients">
        <h2>Ingredients</h2>
        <ul>
          <% @recipe.ingredients.each do |ingredient| %>
            <li>
              <%= ingredient.name %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
    <div class="col-md-4">
      <div id="directions">
        <h2>Directions</h2>
        <ul>
          <% @recipe.directions.each do |direction| %>
            <li>
              <%= direction.step %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
    <% # This has to be for video %>
    <div class="col-md-4">
      <div id="video">
        <h2>
          <%= @recipe.title  %> Video
        </h2>
        <br/>
        <% unless @recipe.video.nil? %>
          <iframe frameborder="0" height="auto" src="https://www.youtube.com/embed/<%= @recipe.youtube_code %>" width="auto"></iframe>
        <% else %>
          <%=image_tag 'missing-video.png', class: 'img-auto' %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <%= link_to "Back", root_path, class: "btn btn-default" %>
      <% if user_signed_in? %>
        <%= link_to "Edit", edit_recipe_path, class: "btn btn-default" %>
        <%= link_to "Delete", recipe_path, method: :delete, data: {confirm: "Are you sure?" }, class: "btn btn-default" %>
      <% end %>
    </div>
  </div>
</div>